context:
  version: 2.0_eb719e71

package:
  name: tblis-dev
  version: ${{ version }}

source:
  git: https://github.com/MatthewsResearchGroup/tblis.git
  rev: "eb719e718976572e0ab53975f4e0c799faeb35f2"


requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - sed
    - python
  host:
    - libhwloc
    - if: linux
      then:
        - libgomp
      else:
        - llvm-openmp


build:
  number: 0
  script:
    file: build.sh
    env:
      TBLIS_ARCH: ${{ "x86_64" if x86_64 else "arm64" if arm64 else "unknown" }}


about:
  summary: Tensor-Based Library Instantiation Software
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/MatthewsResearchGroup/tblis
  repository: https://github.com/MatthewsResearchGroup/tblis
  documentation: https://github.com/MatthewsResearchGroup/tblis

extra:
  recipe-maintainers:
    - chillenb
