context:
  version: 2.0_9b95712

package:
  name: tblis-dev
  version: ${{ version }}

source:
  git: https://github.com/MatthewsResearchGroup/tblis.git
  rev: "9b95712966cb8804be51c62bfd6207957f62bc6f"


requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - sed
    - python
  host:
    - libhwloc
    - if: linux
      then:
        - libgomp
      else:
        - llvm-openmp


build:
  number: 0

about:
  summary: Tensor-Based Library Instantiation Software
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/MatthewsResearchGroup/tblis
  repository: https://github.com/MatthewsResearchGroup/tblis
  documentation: https://github.com/MatthewsResearchGroup/tblis

extra:
  recipe-maintainers:
    - chillenb
