name: Build qcint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        target:
          - linux-64
        os:
          - ubuntu-latest
        packagedir:
          - qcint
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.47.0
          cache: true

      - name: Run code in changed subdirectories
        shell: bash
        env:
          TARGET_PLATFORM: ${{ matrix.target }}
          PACKAGEDIR: ${{ matrix.packagedir }}
          ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_KEY }}

        run: |
          pixi run rattler-build build --recipe-dir $PACKAGEDIR \
            --skip-existing=all --target-platform=$TARGET_PLATFORM \
            -c conda-forge

          # ignore errors because we want to ignore duplicate packages
          for file in output/**/*.conda; do
            pixi run rattler-build upload anaconda -o chillenb "$file" || true
          done
